source "https://rubygems.org"
gem 'rspec'
# gem 'byebug'
# gem 'pry'
# gem 'activesupport'
# # frozen_string_literal: true
# 
# 
# git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
